### PR TITLE
Set the date and location externally and move the map

### PR DESCRIPTION
**Pull request by martinber**
Hi, first of all thank you very much for maintaining this library.

For [my project](https://github.com/martinber/dark-sky-planner) I need to show the sky on a given location and time. (Also I don't want to use the embedded form so I just hide it using CSS).

As far as I know the available methods for configuring time and location are:

- Set location on `config.geopos` before doing `Celestial.display(config)` for the first time.
- Set location using the embedded form (should be done manually by the user).
- Set time using the embedded form (should be done manually by the user).
- Set time using `Celestial.date(date)` (but you can't see the change until the user does some modifications to the embedded form). (Note #20)

I think that adding a `Celestial.location(lat, lon)` function makes sense given that `Celestial.date(date)` already exists. Also, `Celestial.apply()` should move the map if used after any of the previous functions.

Example usage:

```
document.getElementById("go_home").onclick = () => {
    Celestial.date(tonight);
    Celestial.location(home.lat, home.lon);
    Celestial.apply();
}
```

# How I modified Celestial to make it work

I made this issue a Pull Request so you can see a working example of the modifications I did. For now the workaround is:

- Add a `Celestial._location(lat, lon)` function to edit the "lat" and "lon" form input fields.
- Add a `Celestial._go()` function to call the private `go()` function, first I tried to edit the `Celestial.apply()` function and add a call to `go()` there but it didn't work, so I made a new function. 

# Recommendations

I would do some modifications to this library to make it independent from the location and time forms, right now I need to add a hidden `celestial-form` div if I want to set the time and location. Then I would add `Celestial.location(lat, lon)` and make `Celestial.apply()` update the changes.

What do you think? If I take my time I think I can make a better pull request but I don't know the best way to implement it yet.

EDIT: On my project I had to comment out line 2539 of `celestial.js` that says `if (dtpick.isVisible()) return;`. Because of that line I can't change the date because for some reason `dtpick` is visible.

### CODE REVIEW

**Comment by ofrohn** [comment]
I agree that the datetime/location functionality needs some refactoring. I'll change config.location so that it only controls showing the form fields, the date & location settings will always be available and move the map directly. 
The go() function is closely married to the form stuff so I don't think it's a good idea to expose it. Instead of a divorce I prefer to make a new function, say Celestial.skyview(dt, loc) that sets date and location at once and works the same way as go() when called w/o parameters.
Thoughts?

**Comment by martinber** [comment]
`skyview(dt, loc)` without `location=true` is exactly what I need and I think that is the way to go.

Also at the same time I had two more problems with Celestial, I already solved them at least for my use case so I wanted to help a little. I'm going to list them here because I wanted to know what you think.

- The documentation is almost enough, but there are a few things missing or difficult to find for someone like me that never touched Javascript. For example the need to have a "celestial-form" div only if "location=true" (I think). Also the examples on adding data are useful but not enough in some parts. So when I have time I'm going to try submitting a PR

- The other thing is that apart of changing the time and location dinamically I need to add and remove data on the fly. I already made some horrible hacks to make it work enough for me but I'd like to solve it better and upload the changes. So I wanted to know if that feature is out of scope of your program and just leave it on my fork or if you want me to submit PRs. I don't want to bother or waste your time.

Thank you very much!

**Comment by ofrohn** [comment]
Well, the documentation and examples are still a work in progress, as you found out. I'm always open for suggestions! celestial-form is necessary if you have form=true, But the div should be auto-generated if not present. That'll also happen eventually...
As to adding and removing data on the fly, best would be to use the pattern in the "triangle" demo and maintain a json-object of all added data in your code and use Celestial.remove() and then adding the json-data again for every change.
If you want to contribute further, you are very wellcome!

**Comment by ofrohn** [comment]
One more thing: If you make changes to the source code, please do so in the files in the "src" folder, which get combined into celestial.js and celestial.min.js in the main folder by running "node make.js".

**Comment by ofrohn** [comment]
I¡ve implemented the skyview function now, see [here](https://github.com/ofrohn/d3-celestial/issues/20) or in the readme for details

**Pull request merged**
